export const theme = {
  colors: {
    primary: '#1565C0',
    primaryLight: '#1E88E5',
    primaryDark: '#0D47A1',
    secondary: '#00897B',
    secondaryLight: '#26A69A',
    accent: '#FF6B35',
    background: '#F0F4FF',
    surface: '#FFFFFF',
    card: '#FFFFFF',
    text: '#1A1A2E',
    textSecondary: '#5F6368',
    textLight: '#9E9E9E',
    success: '#2E7D32',
    successLight: '#E8F5E9',
    warning: '#E65100',
    warningLight: '#FFF3E0',
    error: '#C62828',
    errorLight: '#FFEBEE',
    border: '#E0E0E0',
    divider: '#EEEEEE',
    shadow: 'rgba(21,101,192,0.15)',

    // Dental condition colors
    caries: '#F44336',
    filling: '#2196F3',
    rct: '#FF9800',
    implant: '#9C27B0',
    aligner: '#4CAF50',
    surgery: '#795548',
    missing: '#9E9E9E',
    crown: '#FFC107',
    healthy: '#E8F5E9',
    selected: '#E3F2FD',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  radius: {
    sm: 6,
    md: 12,
    lg: 16,
    xl: 24,
    round: 50,
  },
  fontSizes: {
    xs: 10,
    sm: 12,
    md: 14,
    lg: 16,
    xl: 18,
    xxl: 22,
    xxxl: 28,
  },
  shadows: {
    sm: {
      shadowColor: '#1565C0',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 4,
      elevation: 3,
    },
    md: {
      shadowColor: '#1565C0',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.12,
      shadowRadius: 8,
      elevation: 6,
    },
    lg: {
      shadowColor: '#1565C0',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.15,
      shadowRadius: 16,
      elevation: 10,
    },
  },
};

export const toothConditions = [
  { key: 'healthy', label: 'Healthy', color: '#4CAF50', icon: 'check-circle' },
  { key: 'caries', label: 'Caries / Decay', color: '#F44336', icon: 'alert-circle' },
  { key: 'filling', label: 'Ceramic Filling', color: '#2196F3', icon: 'square' },
  { key: 'rct', label: 'RCT (Root Canal)', color: '#FF9800', icon: 'git-branch' },
  { key: 'implant', label: 'Implant', color: '#9C27B0', icon: 'anchor' },
  { key: 'aligner', label: 'Tooth Aligner', color: '#00BCD4', icon: 'layers' },
  { key: 'surgery', label: 'Surgery', color: '#795548', icon: 'scissors' },
  { key: 'crown', label: 'Crown / Cap', color: '#FFC107', icon: 'award' },
  { key: 'missing', label: 'Missing Tooth', color: '#9E9E9E', icon: 'x-circle' },
  { key: 'bridge', label: 'Bridge', color: '#607D8B', icon: 'minus' },
];

export const TREATMENT_COSTS = {
  caries: 500,
  filling: 1500,
  rct: 5000,
  implant: 25000,
  aligner: 40000,
  surgery: 10000,
  crown: 8000,
  missing: 0,
  bridge: 12000,
};
